### ISSUE TITLE
Migration from v8 to v10EE

### ISSUE THREAD

**Issue by sudhir-serpentcs** [Elico-Corp/odoo-8.0#175]
## **TODO**

Please check the following link before proceeding to the migration: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

## **Modules to migrate**
When you pick a module, input your github id and the PR number after the name of the module:

- [ ] account_invoice_kanban (OCA/account-invoicing) [#309](https://github.com/OCA/account-invoicing/pull/309)
- [ ] auth_ldap_self_signed #176 
- [ ] ldap_password #177 
- [ ] project_completion_report [hold - wait for v8 refactoring] #181 
- [ ] project_partner_name #180 
- [ ] project_project_category #187 
- [ ] project_task_category (OCA/project) [#313](https://github.com/OCA/project/pull/313)
- [ ] timesheet_activity_report #191 
- [ ] hr_timesheet_auto_creation #182 
- [ ] project_issue_sheet_issue_detail #184 
- [ ] project_timesheet_task_id #183
